### ISSUE TITLE
No model parameter file found

### ISSUE THREAD

**Issue by ijohn12** [decompositional-semantics-initiative/improved-ParaBank-rewriter#4]
Hi,
I got the following error while running paraphrase.sh.

```
[ERROR:root] Uncaught exception
Traceback (most recent call last):
  File "/home/m25dehgh/anaconda3/envs/IMR/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m25dehgh/anaconda3/envs/IMR/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m25dehgh/anaconda3/envs/IMR/lib/python3.8/site-packages/sockeye/translate.py", line 228, in <module>
    main()
  File "/home/m25dehgh/anaconda3/envs/IMR/lib/python3.8/site-packages/sockeye/translate.py", line 41, in main
    run_translate(args)
  File "/home/m25dehgh/anaconda3/envs/IMR/lib/python3.8/site-packages/sockeye/translate.py", line 77, in run_translate
    models, source_vocabs, target_vocab = inference.load_models(
  File "/home/m25dehgh/anaconda3/envs/IMR/lib/python3.8/site-packages/sockeye/inference.py", line 490, in load_models
    inference_model.initialize(batch_size, max_input_len, get_max_output_length)
  File "/home/m25dehgh/anaconda3/envs/IMR/lib/python3.8/site-packages/sockeye/inference.py", line 144, in initialize
    self.load_params_from_file(self.params_fname)
  File "/home/m25dehgh/anaconda3/envs/IMR/lib/python3.8/site-packages/sockeye/model.py", line 174, in load_params_from_file
    utils.check_condition(os.path.exists(fname), "No model parameter file found under %s. "
  File "/home/m25dehgh/anaconda3/envs/IMR/lib/python3.8/site-packages/sockeye/utils.py", line 120, in check_condition
    raise SockeyeError(error_message)
sockeye.utils.SockeyeError: No model parameter file found under ./params.best. This is either not a model directory or the first training checkpoint has not happened yet.
```

I would appreciate it if you could help.

**Comment by kalyan0510** [comment]
U can find under assets: https://github.com/decompositional-semantics-initiative/improved-ParaBank-rewriter/releases/tag/v0.1

https://github.com/decompositional-semantics-initiative/improved-ParaBank-rewriter/releases/download/v0.1/params.best
